# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev

r_binary_packages:
  - rgl

services:
  - xvfb

env:
  global: 
    - RGL_USE_NULL=TRUE
    - DISPLAY=:99.0